version: '3'
services:
  db:
    container_name: postgres-be-radency
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:${DB_PORT}
